version: "3.8"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ahmetfm
      POSTGRES_PASSWORD: ahmet123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "8800:8800"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres-data:
